sudo: required

language: java

jdk:
   - openjdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/bin

# https://github.com/crazy-max/travis-wait-enhanced
before_install: |
  if ! [ -f $HOME/bin/travis-wait-enhanced ]; then
  wget -qO- "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.0.0/travis-wait-enhanced_1.0.0_linux_x86_64.tar.gz" | tar -zxvf - travis-wait-enhanced
  mv travis-wait-enhanced $HOME/bin
  fi


install: /bin/true

jobs:
  include:
  - name: deploy
    if: branch = master AND type = push
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && travis-wait-enhanced --timeout=60m --interval=4m -- mvn -V clean org.apache.maven.plugins:maven-source-plugin:jar-no-fork deploy"

  - name: pr
    if: type = pull_request
    script: "travis-wait-enhanced --timeout=60m --interval=4m -- mvn -V clean org.apache.maven.plugins:maven-source-plugin:jar-no-fork install -Prun-its"
